name: CI
on: [push]

env:
  SEQ_DB: sequelize_test
  SEQ_USER: sequelize_test
  SEQ_PW: sequelize_test

jobs:
  test-mysql-mariadb:
    strategy:
      fail-fast: false
      matrix:
        db:
          - '{ name: "MySQL 5.7", image: "mysql:5.7", dialect: "mysql" }'
          - '{ name: "MariaDB 10.3", image: "mariadb:10.3", dialect: "mariadb" }'
        node-version: [10, 12]
        multiple-runs: [1, 2, 3, 4]
    name: ${{ fromJson(matrix.db).name }} (${{ matrix.multiple-runs }}) (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    services:
      mysql:
        image: ${{ fromJson(matrix.db).image }}
        env:
          MYSQL_DATABASE: sequelize_test
          MYSQL_USER: sequelize_test
          MYSQL_PASSWORD: sequelize_test
          MYSQL_ROOT_PASSWORD: sequelize_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin -usequelize_test -psequelize_test status" --health-interval 10s --health-timeout 5s --health-retries 5 --tmpfs /var/lib/mysql:rw
    env:
      DIALECT: ${{ fromJson(matrix.db).dialect }}
    steps:
      - run: mysql --host 127.0.0.1 --port 3306 -uroot -psequelize_test -e "GRANT ALL ON *.* TO 'sequelize_test'@'%' with grant option; FLUSH PRIVILEGES;"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Unit Tests
        run: npm run test-unit
      - name: Integration Tests
        run: npx mocha --globals setImmediate,clearImmediate --exit --check-leaks --colors -t 30000 --reporter spec "test/integration/transaction.test.js"
